name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

    - name: Build and Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Build and Push ML
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-ml:latest ./ml
        docker push ${{ secrets.DOCKER_USERNAME }}/my-ml:latest